services:

    newt:
        image: fosrl/newt
        container_name: newt
        restart: unless-stopped
        environment:
            - PANGOLIN_ENDPOINT=https://example.com   # Poner email válido
            - NEWT_ID=2ix2t8xk22ubpfy                 # Id copiado
            - NEWT_SECRET=nnisrfsdfc7prqsp9ewo1dvtvci50j5uiqotez00dgap0ii2     # Secret copiado
